### ISSUE TITLE
Hunspell dictionary catalan.dic has extra unneeded slashes (/)

### ISSUE THREAD

**Issue by dimztimz** [Softcatala/catalan-dict-tools#16]
[catalan.dic](https://github.com/Softcatala/catalan-dict-tools/blob/master/resultats/hunspell/catalan.dic) (and the Valencia variant) has about 25000 words that end with slash and there are no flags after that slash. Those slashes are not needed.

If the following commit https://github.com/Softcatala/catalan-dict-tools/commit/e12d944fb65e234888550c3d3507264f50729f2b similar issue was fixed for `catalan.aff`, but it was not fixed in `.dic` file.

**Comment by jaumeortola** [comment]
Thank you. It is fixed now. 

Did you find any problem with these extra slashes? In some programs (e.g. InDesign), the Catalan  dictionaries are slower than they should be, and we haven't found the cause.  

We will do more testing before releasing new versions.

**Comment by dimztimz** [comment]
> Did you find any problem with these extra slashes?

I was testing [Nuspell](https://nuspell.github.io/) with various dictionaries and Nuspell was showing errors because those slashes. Nuspell is a new spellcheking engine that works with the same Hunspell dictionaries. I'm the developer of Nuspell and I already fixed it and relaxed the parser so it accepts "empty" slashes, but still, it is better not to have them. Removing the extra slashes will speed up things for few milliseconds, and more importantly will reduce the file size for ~25kb.

**Comment by dimztimz** [comment]
I tested the new files and the issue is fixed now. I will close it. Thanks for the fast response.
