### ISSUE TITLE
Afegir terme 'sobreajustament'

### ISSUE THREAD

**Issue by joapuiib** [Softcatala/catalan-dict-tools#20]
Seria possible afegir el terme 'sobreajustament' als diccionaris?

- [Viquipèdia: Sobreajustament (overfitting)](https://ca.wikipedia.org/wiki/Sobreajustament_(overfitting))
- [Consulta a Optimot](https://aplicacions.llengua.gencat.cat/llc/AppJava/index.html?action=Principal&method=detall&input_cercar=sobreajustament&numPagina=1&database=TERMCAT&idFont=3481960&idHit=3481960&tipusFont=Diccionaris+terminol%F2gics+del+TERMCAT&numeroResultat=1&databases_avansada=&categories_avansada=&clickLink=detall&titol=sobreajust&tematica=Tecnologies+de+la+informaci%F3+i+la+comunicaci%F3&tipusCerca=cerca.tot#)

No he trobat quin seria el terme per referir-se a 'underfitting'. He estat utilitzant 'subajustament', però no trobe cap referència respecte al seu ús.

**Comment by jaumeortola** [comment]
Moltes gràcies pel comentari. 
En aprenentatge automàtic i intel·ligència artificial tenim un buit de vocabulari consolidat que el Termcat hauria de cobrir com més aviat millor. Jo els he consultat qüestions, que han quedat sense resposta. 

Afegirem sobreajustament al diccionari. 
Per a 'underfitting', una opció seria infraajustament (paral·lel a sobrevalorar/infravalorar, i semblants). S'usa en algunes pàgines web.

**Comment by jaumeortola** [comment]
https://github.com/Softcatala/catalan-dict-tools/commit/a98b599f797cf40ed6b1ebf3e1814ec9ff181918

**Comment by joapuiib** [comment]
Moltes gràcies!

**Comment by joapuiib** [comment]
Crec que els diccionaris de hunspell no s'han actualitzat amb aquests canvis.

- https://github.com/Softcatala/catalan-dict-tools/tree/master/resultats/hunspell

**Comment by jaumeortola** [comment]
> Crec que els diccionaris de hunspell no s'han actualitzat amb aquests canvis.

Sí. Normalment, només actualitzem el diccionari Hunspell quan fem la distribució. Seria això: https://github.com/Softcatala/catalan-dict-tools/commit/0ecdb7ee5b40617945d4ad675b0f8e4c453bc2b4

**Comment by joapuiib** [comment]
Entés. Moltes gràcies!
