### ISSUE TITLE
Terme 'descomentar'

### ISSUE THREAD

**Issue by joapuiib** [Softcatala/catalan-dict-tools#21]
El terme 'descomentar' referent a eliminar un comentari en l'àmbit informàtic no està inclòs en els diccionaris.

No trobe cap referència en cap diccionari, però veig que s'ha utilitzat com a traducció de 'uncomment' en diferents ocasions.

- https://www.softcatala.org/recursos/memories/?source=uncomment&project=

Seria adequat incloure'l en el diccionari?

**Comment by jaumeortola** [comment]
Gràcies, Joan. Ho vam comentar una mica en el canal de Telegram (obert) que tenim per a aquestes qüestions, i l'hem afegit al diccionari.
