### ISSUE TITLE
Suport per a Emacs?

### ISSUE THREAD

**Issue by xbelanch** [Softcatala/catalan-dict-tools#8]
Interessat en saber si disposeu de documentació sobre la integració del diccionari per a Emcas.

**Comment by jaumeortola** [comment]
Pel que veig, Emacs admet diccionaris en format Hunspell.
Per tant, pots agafar els nostres fitxers Hunspell (.aff i .dic) de l'[última versió publicada](https://github.com/Softcatala/catalan-dict-tools/releases) o de la [versió de treball](https://github.com/Softcatala/catalan-dict-tools/tree/master/resultats/hunspell)
El que has de fer és seguir la documentació d'Emacs. Deixo alguns enllaços:
* https://www.emacswiki.org/emacs/InteractiveSpell
* http://wikemacs.org/wiki/Spell_check

**Comment by xbelanch** [comment]
Fet! (i gràcies!) Recomano la lectura de la següent entrada: [https://emacs.stackexchange.com/questions/30008/hunspell-flyspell-and-emacs-on-windows](https://emacs.stackexchange.com/questions/30008/hunspell-flyspell-and-emacs-on-windows) en el supòsit que treballeu l'Emacs en l'entorn Windows.
