### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by albert-astals-cid-kdab** [Softcatala/catalan-dict-tools#9]
It's been more than a year and almost 200 changes since last one

**Comment by tsdgeos** [comment]
Awesome you did a release, thanks :)

**Comment by jaumeortola** [comment]
It is a pre-release.  Some more testing is pending and necessary. I will tell you when it is finished.

**Comment by tsdgeos** [comment]
Ah ok, tell me if i can help somehow

**Comment by jaumeortola** [comment]
Done.
